import Database from 'better-sqlite3';
import path from 'path';
import fs from 'fs';
import {
  Merchant,
  Customer,
  Product,
  Checkout,
  Payment,
  Opportunity,
  Action,
  RevenueAttribution,
  AuditEvent,
  Campaign,
  DashboardMetrics,
} from './types';

const DB_PATH = path.join(process.cwd(), 'revenuepilot.db');

let dbInstance: Database.Database | null = null;

export function getDb(): Database.Database {
  if (!dbInstance) {
    dbInstance = new Database(DB_PATH);
    dbInstance.pragma('journal_mode = WAL');
    dbInstance.pragma('foreign_keys = ON');
    initTables(dbInstance);

    const count = (dbInstance.prepare('SELECT COUNT(*) as c FROM merchants').get() as any)?.c || 0;
    if (count === 0) {
      const { seedDatabase } = require('./seed');
      seedDatabase(false);
    }
  }
  return dbInstance;
}

function initTables(db: Database.Database) {
  // --- Schema-drift migration ---
  // `CREATE TABLE IF NOT EXISTS` never alters an existing table. If a table was
  // created by an older version of this app (missing newer columns), the seed
  // would fail with "no such column". All data is regenerated by seedDatabase on
  // a clean baseline, so on drift we rebuild every table to the canonical schema.
  const canonicalColumns: Record<string, string[]> = {
    merchants: ['id', 'name', 'email', 'currency', 'razorpay_key_id', 'created_at'],
    customers: ['id', 'name', 'email', 'phone', 'lifetime_spend', 'total_orders', 'last_purchase_at', 'segment', 'risk_score', 'created_at'],
    products: ['id', 'name', 'sku', 'category', 'price', 'image_url', 'description', 'inventory', 'order_count', 'total_revenue', 'created_at', 'ai_ready', 'related_product_id', 'related_product_name', 'target_segment', 'cross_sell_confidence'],
    checkouts: ['id', 'customer_id', 'customer_name', 'customer_email', 'cart_items', 'subtotal', 'discount', 'total_amount', 'status', 'step_reached', 'abandoned_at', 'recovery_token', 'recovery_discount_pct', 'created_at', 'updated_at'],
    payments: ['id', 'merchant_id', 'checkout_id', 'customer_id', 'razorpay_order_id', 'razorpay_payment_id', 'razorpay_signature', 'amount', 'currency', 'status', 'failure_code', 'failure_reason', 'failure_description', 'payment_method', 'is_recovery_payment', 'opportunity_id', 'verified_at', 'created_at'],
    opportunities: ['id', 'merchant_id', 'type', 'status', 'priority', 'target_id', 'customer_id', 'amount_at_risk', 'potential_recovery_amount', 'opportunity_score', 'score_factors', 'ai_analysis', 'active_action_id', 'created_at', 'updated_at'],
    actions: ['id', 'opportunity_id', 'type', 'title', 'description', 'config', 'status', 'approved_by', 'approved_at', 'executed_at', 'response_payload', 'created_at'],
    revenue_attributions: ['id', 'opportunity_id', 'action_id', 'payment_id', 'checkout_id', 'amount', 'source', 'confidence_score', 'status', 'attributed_at'],
    audit_events: ['id', 'merchant_id', 'agent_run_id', 'opportunity_id', 'action_id', 'payment_id', 'event_type', 'actor_type', 'metadata', 'created_at'],
    campaigns: ['id', 'name', 'target_segment', 'offer_type', 'discount_pct', 'estimated_reach', 'potential_revenue', 'status', 'agent_rationale', 'created_at'],
  };

  const existing = db.prepare(`SELECT name FROM sqlite_master WHERE type = 'table' AND name NOT LIKE 'sqlite_%'`).all() as { name: string }[];
  let migrationNeeded = false;
  for (const { name } of existing) {
    const canonical = canonicalColumns[name];
    if (!canonical) continue;
    const actual = (db.prepare(`PRAGMA table_info(${name})`).all() as { name: string }[]).map(c => c.name);
    if (JSON.stringify(actual) !== JSON.stringify(canonical)) {
      migrationNeeded = true;
      break;
    }
  }

  if (migrationNeeded) {
    db.exec(`
      DROP TABLE IF EXISTS audit_events;
      DROP TABLE IF EXISTS revenue_attributions;
      DROP TABLE IF EXISTS actions;
      DROP TABLE IF EXISTS opportunities;
      DROP TABLE IF EXISTS payments;
      DROP TABLE IF EXISTS checkouts;
      DROP TABLE IF EXISTS products;
      DROP TABLE IF EXISTS customers;
      DROP TABLE IF EXISTS merchants;
      DROP TABLE IF EXISTS campaigns;
    `);
  }
  // --- End schema-drift migration ---

  db.exec(`
    CREATE TABLE IF NOT EXISTS merchants (
      id TEXT PRIMARY KEY,
      name TEXT NOT NULL,
      email TEXT NOT NULL,
      currency TEXT NOT NULL DEFAULT 'INR',
      razorpay_key_id TEXT NOT NULL,
      created_at TEXT NOT NULL
    );

    CREATE TABLE IF NOT EXISTS customers (
      id TEXT PRIMARY KEY,
      name TEXT NOT NULL,
      email TEXT NOT NULL,
      phone TEXT NOT NULL,
      lifetime_spend REAL NOT NULL DEFAULT 0,
      total_orders INTEGER NOT NULL DEFAULT 0,
      last_purchase_at TEXT,
      segment TEXT NOT NULL DEFAULT 'NEW',
      risk_score REAL NOT NULL DEFAULT 0,
      created_at TEXT NOT NULL
    );

    CREATE TABLE IF NOT EXISTS products (
      id TEXT PRIMARY KEY,
      name TEXT NOT NULL,
      sku TEXT NOT NULL UNIQUE,
      category TEXT NOT NULL,
      price REAL NOT NULL,
      image_url TEXT NOT NULL,
      description TEXT NOT NULL,
      inventory INTEGER NOT NULL DEFAULT 100,
      order_count INTEGER NOT NULL DEFAULT 0,
      total_revenue REAL NOT NULL DEFAULT 0,
      created_at TEXT NOT NULL,
      ai_ready INTEGER DEFAULT 1,
      related_product_id TEXT,
      related_product_name TEXT,
      target_segment TEXT,
      cross_sell_confidence REAL DEFAULT 0.85
    );

    CREATE TABLE IF NOT EXISTS checkouts (
      id TEXT PRIMARY KEY,
      customer_id TEXT NOT NULL,
      customer_name TEXT NOT NULL,
      customer_email TEXT NOT NULL,
      cart_items TEXT NOT NULL, -- JSON
      subtotal REAL NOT NULL,
      discount REAL NOT NULL DEFAULT 0,
      total_amount REAL NOT NULL,
      status TEXT NOT NULL DEFAULT 'IN_PROGRESS',
      step_reached TEXT NOT NULL DEFAULT 'PAYMENT',
      abandoned_at TEXT,
      recovery_token TEXT,
      recovery_discount_pct REAL NOT NULL DEFAULT 0,
      created_at TEXT NOT NULL,
      updated_at TEXT NOT NULL,
      FOREIGN KEY (customer_id) REFERENCES customers (id)
    );

    CREATE TABLE IF NOT EXISTS payments (
      id TEXT PRIMARY KEY,
      merchant_id TEXT NOT NULL,
      checkout_id TEXT,
      customer_id TEXT NOT NULL,
      razorpay_order_id TEXT NOT NULL,
      razorpay_payment_id TEXT,
      razorpay_signature TEXT,
      amount REAL NOT NULL,
      currency TEXT NOT NULL DEFAULT 'INR',
      status TEXT NOT NULL DEFAULT 'CREATED',
      failure_code TEXT,
      failure_reason TEXT,
      failure_description TEXT,
      payment_method TEXT,
      is_recovery_payment INTEGER NOT NULL DEFAULT 0,
      opportunity_id TEXT,
      verified_at TEXT,
      created_at TEXT NOT NULL,
      FOREIGN KEY (customer_id) REFERENCES customers (id)
    );

    CREATE TABLE IF NOT EXISTS opportunities (
      id TEXT PRIMARY KEY,
      merchant_id TEXT NOT NULL,
      type TEXT NOT NULL,
      status TEXT NOT NULL DEFAULT 'DETECTED',
      priority TEXT NOT NULL DEFAULT 'MEDIUM',
      target_id TEXT NOT NULL,
      customer_id TEXT NOT NULL,
      amount_at_risk REAL NOT NULL,
      potential_recovery_amount REAL NOT NULL,
      opportunity_score REAL NOT NULL,
      score_factors TEXT NOT NULL, -- JSON
      ai_analysis TEXT, -- JSON
      active_action_id TEXT,
      created_at TEXT NOT NULL,
      updated_at TEXT NOT NULL,
      FOREIGN KEY (customer_id) REFERENCES customers (id)
    );

    CREATE TABLE IF NOT EXISTS actions (
      id TEXT PRIMARY KEY,
      opportunity_id TEXT NOT NULL,
      type TEXT NOT NULL,
      title TEXT NOT NULL,
      description TEXT NOT NULL,
      config TEXT NOT NULL, -- JSON
      status TEXT NOT NULL DEFAULT 'PENDING_APPROVAL',
      approved_by TEXT,
      approved_at TEXT,
      executed_at TEXT,
      response_payload TEXT, -- JSON
      created_at TEXT NOT NULL,
      FOREIGN KEY (opportunity_id) REFERENCES opportunities (id)
    );

    CREATE TABLE IF NOT EXISTS revenue_attributions (
      id TEXT PRIMARY KEY,
      opportunity_id TEXT NOT NULL,
      action_id TEXT NOT NULL,
      payment_id TEXT NOT NULL,
      checkout_id TEXT,
      amount REAL NOT NULL,
      source TEXT NOT NULL,
      confidence_score REAL NOT NULL DEFAULT 1.0,
      status TEXT NOT NULL DEFAULT 'VERIFIED',
      attributed_at TEXT NOT NULL,
      FOREIGN KEY (opportunity_id) REFERENCES opportunities (id),
      FOREIGN KEY (action_id) REFERENCES actions (id),
      FOREIGN KEY (payment_id) REFERENCES payments (id)
    );

    CREATE TABLE IF NOT EXISTS audit_events (
      id TEXT PRIMARY KEY,
      merchant_id TEXT NOT NULL,
      agent_run_id TEXT NOT NULL,
      opportunity_id TEXT,
      action_id TEXT,
      payment_id TEXT,
      event_type TEXT NOT NULL,
      actor_type TEXT NOT NULL,
      metadata TEXT NOT NULL, -- JSON
      created_at TEXT NOT NULL
    );

    CREATE TABLE IF NOT EXISTS campaigns (
      id TEXT PRIMARY KEY,
      name TEXT NOT NULL,
      target_segment TEXT NOT NULL,
      offer_type TEXT NOT NULL,
      discount_pct REAL NOT NULL DEFAULT 0,
      estimated_reach INTEGER NOT NULL,
      potential_revenue REAL NOT NULL,
      status TEXT NOT NULL DEFAULT 'DRAFT',
      agent_rationale TEXT NOT NULL,
      created_at TEXT NOT NULL
    );

    CREATE INDEX IF NOT EXISTS idx_checkouts_status ON checkouts(status);
    CREATE INDEX IF NOT EXISTS idx_payments_status ON payments(status);
    CREATE INDEX IF NOT EXISTS idx_opps_status ON opportunities(status);
    CREATE INDEX IF NOT EXISTS idx_audit_time ON audit_events(created_at DESC);
  `);
}

// Database helper functions
export const db = {
  // Merchant
  getMerchant(id: string = 'mch_razor_pilot_01'): Merchant | undefined {
    const raw = getDb().prepare('SELECT * FROM merchants WHERE id = ?').get(id) as any;
    return raw;
  },

  // Customers
  getCustomers(): Customer[] {
    return getDb().prepare('SELECT * FROM customers ORDER BY lifetime_spend DESC').all() as Customer[];
  },

  getCustomer(id: string): Customer | undefined {
    return getDb().prepare('SELECT * FROM customers WHERE id = ?').get(id) as Customer | undefined;
  },

  /**
   * Resolve a customer that is guaranteed to exist, so that every checkout,
   * payment and opportunity that references `customer_id` satisfies the foreign
   * key constraint. Priority: (1) exact ID match, (2) email match, (3) create a
   * new customer row. Never returns a non-existent parent.
   */
  getOrCreateCustomer(input?: { id?: string; name?: string; email?: string }): Customer {
    const dbInst = getDb();
    input = input || {};
    const id = input.id || (input.email ? 'cust_' + input.email.split('@')[0] : 'cust_guest');
    if (input.email) {
      const byId = dbInst.prepare('SELECT * FROM customers WHERE id = ?').get(id) as Customer | undefined;
      if (byId) return byId;
      const byEmail = dbInst.prepare('SELECT * FROM customers WHERE email = ?').get(input.email) as Customer | undefined;
      if (byEmail) return byEmail;
    } else if (id) {
      const byId = dbInst.prepare('SELECT * FROM customers WHERE id = ?').get(id) as Customer | undefined;
      if (byId) return byId;
    }

    // No matching parent row -> create one so FK integrity is preserved.
    const now = new Date().toISOString();
    const name = input.name || 'Guest Customer';
    const email = input.email || (id.startsWith('cust_') ? `${id.slice(5)}@example.com` : 'guest@example.com');
    const phone = '+91 90000 00000';
    const createId = 'cust_live_' + Math.random().toString(36).substring(2, 8);
    dbInst.prepare(`
      INSERT INTO customers (id, name, email, phone, lifetime_spend, total_orders, last_purchase_at, segment, risk_score, created_at)
      VALUES (?, ?, ?, ?, 0, 0, NULL, 'NEW', 50, ?)
    `).run(createId, name, email, phone, now);
    return dbInst.prepare('SELECT * FROM customers WHERE id = ?').get(createId) as Customer;
  },

  updateCustomerSpend(id: string, amount: number) {
    const now = new Date().toISOString();
    getDb().prepare(`
      UPDATE customers 
      SET lifetime_spend = lifetime_spend + ?, 
          total_orders = total_orders + 1,
          last_purchase_at = ?,
          segment = CASE 
            WHEN lifetime_spend + ? > 15000 THEN 'HIGH_VALUE'
            WHEN total_orders + 1 >= 3 THEN 'LOYAL'
            ELSE 'NEW'
          END
      WHERE id = ?
    `).run(amount, now, amount, id);
  },

  // Products
  getProducts(): Product[] {
    let prods = getDb().prepare('SELECT * FROM products ORDER BY order_count DESC').all() as Product[];
    if (prods.length === 0) {
      const { seedDatabase } = require('./seed');
      seedDatabase(true);
      prods = getDb().prepare('SELECT * FROM products ORDER BY order_count DESC').all() as Product[];
    }
    return prods;
  },

  getProduct(id: string): Product | undefined {
    return getDb().prepare('SELECT * FROM products WHERE id = ?').get(id) as Product | undefined;
  },

  updateProductSales(id: string, revenue: number) {
    getDb().prepare(`
      UPDATE products 
      SET order_count = order_count + 1, 
          total_revenue = total_revenue + ?,
          inventory = MAX(0, inventory - 1)
      WHERE id = ?
    `).run(revenue, id);
  },

  // Checkouts
  getCheckouts(status?: string): Checkout[] {
    let rows: any[];
    if (status) {
      rows = getDb().prepare('SELECT * FROM checkouts WHERE status = ? ORDER BY created_at DESC').all(status);
    } else {
      rows = getDb().prepare('SELECT * FROM checkouts ORDER BY created_at DESC').all();
    }
    return rows.map(r => ({
      ...r,
      cart_items: JSON.parse(r.cart_items || '[]'),
    }));
  },

  getCheckout(id: string): Checkout | undefined {
    const r = getDb().prepare('SELECT * FROM checkouts WHERE id = ?').get(id) as any;
    if (!r) return undefined;
    return {
      ...r,
      cart_items: JSON.parse(r.cart_items || '[]'),
    };
  },

  getCheckoutByToken(token: string): Checkout | undefined {
    const r = getDb().prepare('SELECT * FROM checkouts WHERE recovery_token = ?').get(token) as any;
    if (!r) return undefined;
    return {
      ...r,
      cart_items: JSON.parse(r.cart_items || '[]'),
    };
  },

  createCheckout(data: Omit<Checkout, 'created_at' | 'updated_at'>): Checkout {
    const now = new Date().toISOString();
    getDb().prepare(`
      INSERT INTO checkouts (id, customer_id, customer_name, customer_email, cart_items, subtotal, discount, total_amount, status, step_reached, abandoned_at, recovery_token, recovery_discount_pct, created_at, updated_at)
      VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
    `).run(
      data.id,
      data.customer_id,
      data.customer_name,
      data.customer_email,
      JSON.stringify(data.cart_items),
      data.subtotal,
      data.discount,
      data.total_amount,
      data.status,
      data.step_reached,
      data.abandoned_at,
      data.recovery_token,
      data.recovery_discount_pct,
      now,
      now
    );
    return { ...data, created_at: now, updated_at: now };
  },

  updateCheckoutStatus(id: string, status: string, recoveryToken?: string) {
    const now = new Date().toISOString();
    if (recoveryToken !== undefined) {
      getDb().prepare('UPDATE checkouts SET status = ?, recovery_token = ?, updated_at = ? WHERE id = ?').run(status, recoveryToken, now, id);
    } else {
      getDb().prepare('UPDATE checkouts SET status = ?, updated_at = ? WHERE id = ?').run(status, now, id);
    }
  },

  // Payments
  getPayments(): Payment[] {
    const rows = getDb().prepare(`
      SELECT p.*, c.name as customer_name 
      FROM payments p
      LEFT JOIN customers c ON p.customer_id = c.id
      ORDER BY p.created_at DESC
    `).all() as any[];
    return rows.map(r => ({
      ...r,
      is_recovery_payment: Boolean(r.is_recovery_payment),
    }));
  },

  getPayment(id: string): Payment | undefined {
    const r = getDb().prepare(`
      SELECT p.*, c.name as customer_name 
      FROM payments p
      LEFT JOIN customers c ON p.customer_id = c.id
      WHERE p.id = ?
    `).get(id) as any;
    if (!r) return undefined;
    return {
      ...r,
      is_recovery_payment: Boolean(r.is_recovery_payment),
    };
  },

  getPaymentByOrderId(orderId: string): Payment | undefined {
    const r = getDb().prepare('SELECT * FROM payments WHERE razorpay_order_id = ?').get(orderId) as any;
    if (!r) return undefined;
    return {
      ...r,
      is_recovery_payment: Boolean(r.is_recovery_payment),
    };
  },

  createPayment(data: Omit<Payment, 'created_at'>): Payment {
    const now = new Date().toISOString();
    getDb().prepare(`
      INSERT INTO payments (id, merchant_id, checkout_id, customer_id, razorpay_order_id, razorpay_payment_id, razorpay_signature, amount, currency, status, failure_code, failure_reason, failure_description, payment_method, is_recovery_payment, opportunity_id, verified_at, created_at)
      VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
    `).run(
      data.id,
      data.merchant_id,
      data.checkout_id,
      data.customer_id,
      data.razorpay_order_id,
      data.razorpay_payment_id,
      data.razorpay_signature,
      data.amount,
      data.currency || 'INR',
      data.status,
      data.failure_code,
      data.failure_reason,
      data.failure_description,
      data.payment_method,
      data.is_recovery_payment ? 1 : 0,
      data.opportunity_id,
      data.verified_at,
      now
    );
    return { ...data, created_at: now };
  },

  updatePaymentSuccess(id: string, paymentId: string, signature: string) {
    const now = new Date().toISOString();
    getDb().prepare(`
      UPDATE payments 
      SET status = 'CAPTURED', 
          razorpay_payment_id = ?, 
          razorpay_signature = ?, 
          verified_at = ?
      WHERE id = ?
    `).run(paymentId, signature, now, id);
  },

  updatePaymentFailure(id: string, code: string, reason: string, desc: string) {
    getDb().prepare(`
      UPDATE payments 
      SET status = 'FAILED', 
          failure_code = ?, 
          failure_reason = ?, 
          failure_description = ?
      WHERE id = ?
    `).run(code, reason, desc, id);
  },

  // Opportunities
  getOpportunities(status?: string): Opportunity[] {
    let rows: any[];
    if (status) {
      rows = getDb().prepare(`
        SELECT o.*, c.name as customer_name, c.email as customer_email
        FROM opportunities o
        LEFT JOIN customers c ON o.customer_id = c.id
        WHERE o.status = ?
        ORDER BY o.opportunity_score DESC, o.created_at DESC
      `).all(status);
    } else {
      rows = getDb().prepare(`
        SELECT o.*, c.name as customer_name, c.email as customer_email
        FROM opportunities o
        LEFT JOIN customers c ON o.customer_id = c.id
        ORDER BY o.opportunity_score DESC, o.created_at DESC
      `).all();
    }
    return rows.map(r => ({
      ...r,
      score_factors: JSON.parse(r.score_factors || '[]'),
      ai_analysis: r.ai_analysis ? JSON.parse(r.ai_analysis) : null,
    }));
  },

  getOpportunity(id: string): Opportunity | undefined {
    const r = getDb().prepare(`
      SELECT o.*, c.name as customer_name, c.email as customer_email
      FROM opportunities o
      LEFT JOIN customers c ON o.customer_id = c.id
      WHERE o.id = ?
    `).get(id) as any;
    if (!r) return undefined;
    return {
      ...r,
      score_factors: JSON.parse(r.score_factors || '[]'),
      ai_analysis: r.ai_analysis ? JSON.parse(r.ai_analysis) : null,
    };
  },

  getOpportunityByTargetId(targetId: string): Opportunity | undefined {
    const r = getDb().prepare(`
      SELECT o.*, c.name as customer_name, c.email as customer_email
      FROM opportunities o
      LEFT JOIN customers c ON o.customer_id = c.id
      WHERE o.target_id = ?
    `).get(targetId) as any;
    if (!r) return undefined;
    return {
      ...r,
      score_factors: JSON.parse(r.score_factors || '[]'),
      ai_analysis: r.ai_analysis ? JSON.parse(r.ai_analysis) : null,
    };
  },

  createOpportunity(data: Omit<Opportunity, 'created_at' | 'updated_at'>): Opportunity {
    const now = new Date().toISOString();
    getDb().prepare(`
      INSERT INTO opportunities (id, merchant_id, type, status, priority, target_id, customer_id, amount_at_risk, potential_recovery_amount, opportunity_score, score_factors, ai_analysis, active_action_id, created_at, updated_at)
      VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
    `).run(
      data.id,
      data.merchant_id,
      data.type,
      data.status,
      data.priority,
      data.target_id,
      data.customer_id,
      data.amount_at_risk,
      data.potential_recovery_amount,
      data.opportunity_score,
      JSON.stringify(data.score_factors),
      data.ai_analysis ? JSON.stringify(data.ai_analysis) : null,
      data.active_action_id || null,
      now,
      now
    );
    return { ...data, created_at: now, updated_at: now };
  },

  updateOpportunity(id: string, updates: Partial<Opportunity>) {
    const now = new Date().toISOString();
    const fields: string[] = [];
    const values: any[] = [];

    if (updates.status !== undefined) {
      fields.push('status = ?');
      values.push(updates.status);
    }
    if (updates.priority !== undefined) {
      fields.push('priority = ?');
      values.push(updates.priority);
    }
    if (updates.opportunity_score !== undefined) {
      fields.push('opportunity_score = ?');
      values.push(updates.opportunity_score);
    }
    if (updates.score_factors !== undefined) {
      fields.push('score_factors = ?');
      values.push(JSON.stringify(updates.score_factors));
    }
    if (updates.ai_analysis !== undefined) {
      fields.push('ai_analysis = ?');
      values.push(JSON.stringify(updates.ai_analysis));
    }
    if (updates.active_action_id !== undefined) {
      fields.push('active_action_id = ?');
      values.push(updates.active_action_id);
    }

    fields.push('updated_at = ?');
    values.push(now);
    values.push(id);

    if (fields.length > 1) {
      getDb().prepare(`UPDATE opportunities SET ${fields.join(', ')} WHERE id = ?`).run(...values);
    }
  },

  // Actions
  getActions(opportunityId?: string): Action[] {
    let rows: any[];
    if (opportunityId) {
      rows = getDb().prepare('SELECT * FROM actions WHERE opportunity_id = ? ORDER BY created_at DESC').all(opportunityId);
    } else {
      rows = getDb().prepare('SELECT * FROM actions ORDER BY created_at DESC').all();
    }
    return rows.map(r => ({
      ...r,
      config: JSON.parse(r.config || '{}'),
      response_payload: r.response_payload ? JSON.parse(r.response_payload) : null,
    }));
  },

  getAction(id: string): Action | undefined {
    const r = getDb().prepare('SELECT * FROM actions WHERE id = ?').get(id) as any;
    if (!r) return undefined;
    return {
      ...r,
      config: JSON.parse(r.config || '{}'),
      response_payload: r.response_payload ? JSON.parse(r.response_payload) : null,
    };
  },

  createAction(data: Omit<Action, 'created_at'>): Action {
    const now = new Date().toISOString();
    getDb().prepare(`
      INSERT INTO actions (id, opportunity_id, type, title, description, config, status, approved_by, approved_at, executed_at, response_payload, created_at)
      VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
    `).run(
      data.id,
      data.opportunity_id,
      data.type,
      data.title,
      data.description,
      JSON.stringify(data.config),
      data.status,
      data.approved_by,
      data.approved_at,
      data.executed_at,
      data.response_payload ? JSON.stringify(data.response_payload) : null,
      now
    );
    return { ...data, created_at: now };
  },

  updateActionStatus(id: string, status: string, approvedBy?: string, responsePayload?: any) {
    const now = new Date().toISOString();
    if (status === 'APPROVED' || status === 'EXECUTED') {
      getDb().prepare(`
        UPDATE actions 
        SET status = ?, 
            approved_by = COALESCE(?, approved_by), 
            approved_at = COALESCE(approved_at, ?),
            executed_at = ?,
            response_payload = COALESCE(?, response_payload)
        WHERE id = ?
      `).run(status, approvedBy || null, now, now, responsePayload ? JSON.stringify(responsePayload) : null, id);
    } else {
      getDb().prepare('UPDATE actions SET status = ? WHERE id = ?').run(status, id);
    }
  },

  // Revenue Attribution
  createAttribution(data: RevenueAttribution): RevenueAttribution {
    getDb().prepare(`
      INSERT INTO revenue_attributions (id, opportunity_id, action_id, payment_id, checkout_id, amount, source, confidence_score, status, attributed_at)
      VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
    `).run(
      data.id,
      data.opportunity_id,
      data.action_id,
      data.payment_id,
      data.checkout_id,
      data.amount,
      data.source,
      data.confidence_score,
      data.status,
      data.attributed_at
    );
    return data;
  },

  getAttributions(): RevenueAttribution[] {
    return getDb().prepare('SELECT * FROM revenue_attributions ORDER BY attributed_at DESC').all() as RevenueAttribution[];
  },

  // Audit Events
  recordAudit(data: Omit<AuditEvent, 'id' | 'created_at'>): AuditEvent {
    const id = 'aud_' + Math.random().toString(36).substring(2, 9) + '_' + Date.now();
    const now = new Date().toISOString();
    getDb().prepare(`
      INSERT INTO audit_events (id, merchant_id, agent_run_id, opportunity_id, action_id, payment_id, event_type, actor_type, metadata, created_at)
      VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
    `).run(
      id,
      data.merchant_id || 'mch_razor_pilot_01',
      data.agent_run_id,
      data.opportunity_id || null,
      data.action_id || null,
      data.payment_id || null,
      data.event_type,
      data.actor_type,
      JSON.stringify(data.metadata || {}),
      now
    );
    return {
      id,
      merchant_id: data.merchant_id || 'mch_razor_pilot_01',
      agent_run_id: data.agent_run_id,
      opportunity_id: data.opportunity_id || null,
      action_id: data.action_id || null,
      payment_id: data.payment_id || null,
      event_type: data.event_type,
      actor_type: data.actor_type,
      metadata: data.metadata || {},
      created_at: now,
    };
  },

  getAuditEvents(limit: number = 100, opportunityId?: string): AuditEvent[] {
    let rows: any[];
    if (opportunityId) {
      rows = getDb().prepare('SELECT * FROM audit_events WHERE opportunity_id = ? ORDER BY created_at DESC LIMIT ?').all(opportunityId, limit);
    } else {
      rows = getDb().prepare('SELECT * FROM audit_events ORDER BY created_at DESC LIMIT ?').all(limit);
    }
    return rows.map(r => ({
      ...r,
      metadata: JSON.parse(r.metadata || '{}'),
    }));
  },

  // Campaigns
  getCampaigns(): Campaign[] {
    return getDb().prepare('SELECT * FROM campaigns ORDER BY created_at DESC').all() as Campaign[];
  },

  createCampaign(data: Campaign): Campaign {
    getDb().prepare(`
      INSERT INTO campaigns (id, name, target_segment, offer_type, discount_pct, estimated_reach, potential_revenue, status, agent_rationale, created_at)
      VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
    `).run(
      data.id,
      data.name,
      data.target_segment,
      data.offer_type,
      data.discount_pct,
      data.estimated_reach,
      data.potential_revenue,
      data.status,
      data.agent_rationale,
      data.created_at
    );
    return data;
  },

  // Deterministic Metrics Calculation
  getMetrics(): DashboardMetrics {
    const totalCaptured = getDb().prepare(`
      SELECT COALESCE(SUM(amount), 0) as total 
      FROM payments 
      WHERE status = 'CAPTURED'
    `).get() as { total: number };

    const recovered = getDb().prepare(`
      SELECT COALESCE(SUM(amount), 0) as total 
      FROM revenue_attributions
    `).get() as { total: number };

    const atRisk = getDb().prepare(`
      SELECT COALESCE(SUM(amount_at_risk), 0) as total 
      FROM opportunities 
      WHERE status IN ('DETECTED', 'ANALYZING', 'PENDING_APPROVAL', 'APPROVED', 'ACTION_CREATED')
    `).get() as { total: number };

    const activeOpps = getDb().prepare(`
      SELECT COUNT(*) as count 
      FROM opportunities 
      WHERE status IN ('DETECTED', 'ANALYZING', 'PENDING_APPROVAL', 'APPROVED', 'ACTION_CREATED')
    `).get() as { count: number };

    const failedPayments = getDb().prepare(`
      SELECT COUNT(*) as count 
      FROM payments 
      WHERE status = 'FAILED'
    `).get() as { count: number };

    const abandonedCheckouts = getDb().prepare(`
      SELECT COUNT(*) as count 
      FROM checkouts 
      WHERE status = 'ABANDONED'
    `).get() as { count: number };

    const recoveredCount = getDb().prepare(`
      SELECT COUNT(*) as count 
      FROM opportunities 
      WHERE status = 'RECOVERED'
    `).get() as { count: number };

    const totalCapturedCount = getDb().prepare(`
      SELECT COUNT(*) as count 
      FROM payments 
      WHERE status = 'CAPTURED'
    `).get() as { count: number };

    const potentialGrowth = getDb().prepare(`
      SELECT COALESCE(SUM(potential_recovery_amount), 0) as total 
      FROM opportunities 
      WHERE status IN ('DETECTED', 'ANALYZING', 'PENDING_APPROVAL', 'APPROVED', 'ACTION_CREATED')
    `).get() as { total: number };

    const totalLostOrRecoveredCount = abandonedCheckouts.count + failedPayments.count + recoveredCount.count;
    const recoveryRate = totalLostOrRecoveredCount > 0 
      ? Math.round((recoveredCount.count / totalLostOrRecoveredCount) * 100) 
      : 0;

    const avgOrderValue = totalCapturedCount.count > 0 
      ? Math.round(totalCaptured.total / totalCapturedCount.count)
      : 4999;

    return {
      total_revenue: totalCaptured.total,
      recovered_revenue: recovered.total,
      ai_attributed_revenue: recovered.total,
      revenue_at_risk: atRisk.total,
      potential_growth_revenue: potentialGrowth.total,
      average_order_value: avgOrderValue,
      active_opportunities_count: activeOpps.count,
      recovery_rate_pct: recoveryRate,
      failed_payment_count: failedPayments.count,
      abandoned_checkout_count: abandonedCheckouts.count,
      recovered_count: recoveredCount.count,
    };
  },
};
